image: golang:latest

variables:
  OUT_DIR: "deployer-build"

build:
    stage: build
    script:
      - mkdir $OUT_DIR
      - GOOS=linux GOARCH=386 go build -ldflags "-s -w" -o $OUT_DIR/deployer-386
      - GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o $OUT_DIR/deployer-amd64
      - GOOS=linux GOARCH=arm go build -ldflags "-s -w" -o $OUT_DIR/deployer-arm
      - GOOS=linux GOARCH=arm64 go build -ldflags "-s -w" -o $OUT_DIR/deployer-arm64
      - GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o $OUT_DIR/deployer-amd64.exe
    artifacts:
      paths:
        - $OUT_DIR
