before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  - format: binary
checksum:
  name_template: "checksums-arm.txt"
release:
  prerelease: auto
