before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
archives:
  - format: binary
checksum:
  name_template: "checksums-amd.txt"
release:
  prerelease: auto
