name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.API_GITHUB_TOKEN }}

      - name: Docker Prepare
        if: success()
        uses: crazy-max/ghaction-docker-buildx@v3.3.1

      - name: Docker Build Test
        if: success()
        run: docker buildx build --load --tag test:test --file ./Dockerfile ./

      - name: Version
        if: success()
        uses: cycjimmy/semantic-release-action@v2.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
